#ifndef myoptions_h
#define myoptions_h

/* Generated by myoptions.h generator - v0.8.1 */
/* https://e2002.github.io/docs/myoptions-generator.html?r=71,1,4,9,45,54&i=28,29,30&v=36,34,39 */
/* Put this file next to yoRadio.ino and restart Arduino IDE. */

/* !!! Attention !!! */
/* This configuration depends on some additional libraries. Please install them using the library manager: */
/* OneButton */

/* !!! Do not be alarmed, all right, the default values ​​are not included in this file !!! */

#define DSP_MODEL           DSP_ILI9341
#define L10N_LANGUAGE       RU
#define TFT_DC              2
#define TFT_CS              21
#define BRIGHTNESS_PIN      22
#define ENC_BTNR            36
#define ENC_BTNL            34
#define ENC_BTNB            39
#define ENC_INTERNALPULLUP  false

#define UART_TX             4
#define UART_RX             5
#define BTN_QR              35
#define BTN_F1              15
#define BTN_F2              14
#define BTN_F3              12
#define BTN_F4              33
#define BTN_F5              32
#define BTN_F6              0
#define BUZZER              13
#define BATTERY_SHOW_ON
#endif
